services:
  web:
    build: docker/web
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "bun install && bun dev"

  api:
    build: docker/api
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    ports:
      - "8787:8787"
    command: sh -c "bun install && bun dev"
