services:
  web:
    build: docker/web
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    command: sh -c "yarn install && yarn dev"

  api:
    build: docker/api
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    ports:
      - "8787:8787"
    command: sh -c "yarn install && yarn dev"
